extends Node2D
# head arms body legs tail wings
var kaiju_template = {
	"types": ["fire", "organic"],
	"anatomy": ["head", "arms", "body", "legs", "tail", "wings"],
	"tier": 1,
	"anatomy_map": { #Generated by varying the tier around the base tier.
		"head": 1,
		"arms": 1,
		"body": 1,
		"legs": 1,
		"tail": 1,
		"wings": 1,
	},
	"apocalypse_decks": ["head", "body"]
}
var library = KaijuLibrary.library

var decks = []

func generate_deck(anatomy, types):
	var deck_list = []
	#switch with random weights instead of tier only...but for now just check the tiers.

	return deck_list

func generate_decks():
	var tiers = kaiju_template["anatomy_map"]
	for key in tiers.keys():
		#Instantiate a deck object and put it into the right position on the board. For now we're just going to assign to existing buttons in the scene.
		if key == "head":
			pass
		if key == "body":
			pass
		if key == "tail":
			pass
		if key == "wings":
			pass
		if key == "legs":
			pass
		if key == "arms":
			pass
		pass
	#anatomy_map works as our weighted options



# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
